// Generated by CoffeeScript 1.6.1

/*
CRUD findOne
*/


(function() {
  var _;

  _ = require('lodash');

  module.exports = function(options) {
    return function(request, reply) {
      var Model, callback, params;
      params = _.merge(request.query, request.params);
      Model = options.model;
      callback = function(err, model) {
        if (err) {
          return reply(request.hapi.Error.internal(err));
        }
        if (!model) {
          return reply(request.hapi.Error.notFound("model searched for by " + JSON.stringify(params) + " not found"));
        }
        return reply(model);
      };
      if (request.pre.model || _.isNull(request.pre.model)) {
        return callback(null, request.pre.model);
      } else {
        return Model.findOne(params).exec(callback);
      }
    };
  };

}).call(this);
